item = {
    "id" : "s",
    "character_restriction" : "s",
    "flags" : "t",
    "type" : "s",
    "category" : "b",
    "data_1": "d7",

    "target_type?": "b",
    "range?": "f",
    "area?": "b",
    "float_1?": "f",
    "float_2?": "f",
    "float_3?": "f",

    "effect1_id" : "s",
    "effect1_data1" : "i",
    "effect1_data2" : "i",
    "effect1_data3" : "i",
    "effect2_id" : "s",
    "effect2_data1" : "i",
    "effect2_data2" : "i",
    "effect2_data3" : "i",
    "effect3_id" : "s",
    "effect3_data1" : "i",
    "effect3_data2" : "i",
    "effect3_data3" : "i",
    "effect4_id" : "s",
    "effect4_data1" : "i",
    "effect4_data2" : "i",
    "effect4_data3" : "i",
    "effect5_id" : "s",
    "effect5_data1" : "i",
    "effect5_data2" : "i",
    "effect5_data3" : "i",

    "str": "s",
    "def": "s",
    "ats": "s",
    "adf": "s",
    "acc": "s",
    "eva": "s",
    "spd": "s",
    "mov": "s",
    "hp": "s",
    "ep": "s",
    "price": "i",
    "carry_limit": "b",
    "sort_id": "s",

    "short_xx0": "s",
    "name": "t",
    "description": "t",
    "zeros": "d"
}

item_q = {
    "id" : "s",
    "character_restriction" : "s",
    "flags" : "t",
    "unknown" : "s",
    "data_1" : "d2",
    "element": "s",
    "data_def": "d4",
    "short_x": "s",
    "data": "d115",
    "name": "t",
    "description": "t",
    "end": "d",
}

headers = ["item", "item_q"]