item = {
    "id" : "s",
    "character_restriction" : "s",
    "flags" : "t",
    "unknown" : "s",
    "category" : "b",
    "data_1": "d8",
    "range?": "f",
    "data_2": "d5",
    "float_2": "f",
    "float_3": "f",
    "effect_id": "s",
    "effect_parameter": "s",
    "data_3": "d2",
    "ep_restore?": "s",
    "data_4": "d2",
    "cp_restore?": "s",
    "data_5": "d14",
    "short_2": "s",
    "data_6" : "d6",
    "short_3": "s",
    "data" : "d54",
    "price?": "s",
    "data_xx": "d2",
    "carry_max?": "b",
    "sort_id?": "s",
    "short_xx0": "s",
    "name": "t",
    "description": "t",
    "zeros": "d"
}

item_q = {
    "id" : "s",
    "character_restriction" : "s",
    "flags" : "t",
    "unknown" : "s",
    "data_1" : "d2",
    "element": "s",
    "data_def": "d4",
    "short_x": "s",
    "data": "d115",
    "name": "t",
    "description": "t",
    "end": "d",
}

headers = ["item", "item_q"]